### ISSUE TITLE
Data pack not working on 1.21.4

### ISSUE THREAD

**Issue by Jsaunders411** [mFireworks/RenewableResources#1]
4.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:brain_coral_block' from 'minecraft:recipe/brain_coral_block.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:brain_coral_fan"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:brain_coral_fan"}; Second: Not a string: {"item":"minecraft:brain_coral_fan"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:bubble_coral_block' from 'minecraft:recipe/bubble_coral_block.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:bubble_coral_fan"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:bubble_coral_fan"}; Second: Not a string: {"item":"minecraft:bubble_coral_fan"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:calcite' from 'minecraft:recipe/calcite.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:quartz"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:quartz"}; Second: Not a string: {"item":"minecraft:quartz"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:coal_ore' from 'minecraft:recipe/coal_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:coal"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:coal"}; Second: Not a string: {"item":"minecraft:coal"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:cobweb' from 'minecraft:recipe/cobweb.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:string"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:string"}; Second: Not a string: {"item":"minecraft:string"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:copper_ore' from 'minecraft:recipe/copper_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:copper_block"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:copper_block"}; Second: Not a string: {"item":"minecraft:copper_block"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:dead_bush' from 'minecraft:recipe/dead_bush.json': DataResult.Error['List is too short: 0, expected range [1-9]']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:deepslate' from 'minecraft:recipe/deepslate.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:blackstone"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:blackstone"}; Second: Not a string: {"item":"minecraft:blackstone"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:deepslate_coal_ore' from 'minecraft:recipe/deepslate_coal_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:coal"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:coal"}; Second: Not a string: {"item":"minecraft:coal"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:deepslate_copper_ore' from 'minecraft:recipe/deepslate_copper_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:copper_block"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:copper_block"}; Second: Not a string: {"item":"minecraft:copper_block"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:deepslate_diamond_ore' from 'minecraft:recipe/deepslate_diamond_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:diamond"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:diamond"}; Second: Not a string: {"item":"minecraft:diamond"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:deepslate_emerald_ore' from 'minecraft:recipe/deepslate_emerald_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:emerald"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:emerald"}; Second: Not a string: {"item":"minecraft:emerald"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:deepslate_gold_ore' from 'minecraft:recipe/deepslate_gold_ore.json': DataResult.Error['Map entry 'g' : Failed to parse either. First: Not a string: {"item":"minecraft:gold_ingot"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:gold_ingot"}; Second: Not a string: {"item":"minecraft:gold_ingot"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:deepslate_iron_ore' from 'minecraft:recipe/deepslate_iron_ore.json': DataResult.Error['Map entry 'i' : Failed to parse either. First: Not a string: {"item":"minecraft:iron_ingot"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:iron_ingot"}; Second: Not a string: {"item":"minecraft:iron_ingot"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:deepslate_lapis_ore' from 'minecraft:recipe/deepslate_lapis_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:lapis_block"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:lapis_block"}; Second: Not a string: {"item":"minecraft:lapis_block"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:deepslate_redstone_ore' from 'minecraft:recipe/deepslate_redstone_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:redstone_block"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:redstone_block"}; Second: Not a string: {"item":"minecraft:redstone_block"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:diamond_horse_armor' from 'minecraft:recipe/diamond_horse_armor.json': DataResult.Error['Map entry 'd' : Failed to parse either. First: Not a string: {"item":"minecraft:diamond"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:diamond"}; Second: Not a string: {"item":"minecraft:diamond"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:diamond_ore' from 'minecraft:recipe/diamond_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:diamond"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:diamond"}; Second: Not a string: {"item":"minecraft:diamond"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:dirt' from 'minecraft:recipe/dirt.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:gravel"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:gravel"}; Second: Not a string: {"item":"minecraft:gravel"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:emerald_ore' from 'minecraft:recipe/emerald_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:emerald"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:emerald"}; Second: Not a string: {"item":"minecraft:emerald"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:end_stone' from 'minecraft:recipe/end_stone.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:blaze_powder"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:blaze_powder"}; Second: Not a string: {"item":"minecraft:blaze_powder"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:fire_coral_block' from 'minecraft:recipe/fire_coral_block.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:fire_coral_fan"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:fire_coral_fan"}; Second: Not a string: {"item":"minecraft:fire_coral_fan"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:gilded_blackstone' from 'minecraft:recipe/gilded_blackstone.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:gold_nugget"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:gold_nugget"}; Second: Not a string: {"item":"minecraft:gold_nugget"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:gold_ore' from 'minecraft:recipe/gold_ore.json': DataResult.Error['Map entry 'g' : Failed to parse either. First: Not a string: {"item":"minecraft:gold_ingot"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:gold_ingot"}; Second: Not a string: {"item":"minecraft:gold_ingot"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:golden_horse_armor' from 'minecraft:recipe/golden_horse_armor.json': DataResult.Error['Map entry 'g' : Failed to parse either. First: Not a string: {"item":"minecraft:gold_ingot"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:gold_ingot"}; Second: Not a string: {"item":"minecraft:gold_ingot"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:horn_coral_block' from 'minecraft:recipe/horn_coral_block.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:horn_coral_fan"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:horn_coral_fan"}; Second: Not a string: {"item":"minecraft:horn_coral_fan"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:iron_horse_armor' from 'minecraft:recipe/iron_horse_armor.json': DataResult.Error['Map entry 'i' : Failed to parse either. First: Not a string: {"item":"minecraft:iron_ingot"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:iron_ingot"}; Second: Not a string: {"item":"minecraft:iron_ingot"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:iron_ore' from 'minecraft:recipe/iron_ore.json': DataResult.Error['Map entry 'i' : Failed to parse either. First: Not a string: {"item":"minecraft:iron_ingot"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:iron_ingot"}; Second: Not a string: {"item":"minecraft:iron_ingot"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:lapis_lazuli_ore' from 'minecraft:recipe/lapis_lazuli_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:lapis_block"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:lapis_block"}; Second: Not a string: {"item":"minecraft:lapis_block"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:nether_gold_ore' from 'minecraft:recipe/nether_gold_ore.json': DataResult.Error['Map entry 'g' : Failed to parse either. First: Not a string: {"item":"minecraft:gold_ingot"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:gold_ingot"}; Second: Not a string: {"item":"minecraft:gold_ingot"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:nether_quartz_ore' from 'minecraft:recipe/nether_quartz_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:quartz"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:quartz"}; Second: Not a string: {"item":"minecraft:quartz"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:netherrack' from 'minecraft:recipe/netherrack.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:nether_wart"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:nether_wart"}; Second: Not a string: {"item":"minecraft:nether_wart"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:red_sand' from 'minecraft:recipe/red_sand.json': DataResult.Error['List is too short: 0, expected range [1-9]']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:redstone_ore' from 'minecraft:recipe/redstone_ore.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:redstone_block"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:redstone_block"}; Second: Not a string: {"item":"minecraft:redstone_block"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:rooted_dirt' from 'minecraft:recipe/rooted_dirt.json': DataResult.Error['Map entry 'R' : Failed to parse either. First: Not a string: {"item":"minecraft:hanging_roots"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:hanging_roots"}; Second: Not a string: {"item":"minecraft:hanging_roots"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:small_dripleaf' from 'minecraft:recipe/small_dripleaf.json': DataResult.Error['List is too short: 0, expected range [1-9]']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:spore_blossom' from 'minecraft:recipe/spore_blossom.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:small_dripleaf"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:small_dripleaf"}; Second: Not a string: {"item":"minecraft:small_dripleaf"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:tube_coral_block' from 'minecraft:recipe/tube_coral_block.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:tube_coral_fan"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:tube_coral_fan"}; Second: Not a string: {"item":"minecraft:tube_coral_fan"}']
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'minecraft:tuff' from 'minecraft:recipe/tuff.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Not a string: {"item":"minecraft:cobbled_deepslate"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:cobbled_deepslate"}; Second: Not a string: {"item":"minecraft:cobbled_deepslate"}']
14.12 00:12:34 [Server] ERROR Invalid path in pack: global:advancement/(namespace).json, ignoring
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'global:datapack_info' from 'global:advancement/datapack_info.json': DataResult.Error['No key id in MapLike[{"item":"stone"}]': Advancement[parent=Optional[global:namespace], display=Optional.empty, rewards=AdvancementRewards[experience=0, loot=[], recipes=[], function=Optional.empty], criteria={trigger=Criterion[trigger=net.minecraft.advancements.critereon.PlayerTrigger@6062b101, triggerInstance=TriggerInstance[player=Optional.empty]]}, requirements=[[trigger]], sendsTelemetryEvent=false, name=Optional.empty]]
14.12 00:12:34 [Server] ERROR Couldn't parse data file 'global:namespace' from 'global:advancement/namespace.json': DataResult.Error['No key id in MapLike[{"item":"minecraft:player_head","nbt":"{SkullOwner: 'AtlasPlays'}"}]': Advancement[parent=Optional[global:root], display=Optional.empty, rewards=AdvancementRewards[experience=0, loot=[], recipes=[], function=Optional.empty], criteria={trigger=Criterion[trigger=net.minecraft.advancements.critereon.PlayerTrigger@6062b101, triggerInstance=TriggerInstance[player=Optional.empty]]}, requirements=[[trigger]], sendsTelemetryEvent=false, name=Optional.empty]]

**Comment by mFireworks** [comment]
The datapack hasn't been updated to 1.21.4 yet, looks like there's some breaking changes.

I have an idea of what's wrong, so updating it shouldn't take long.

**Comment by Jsaunders411** [comment]
appreciate the quick response figured it wasn't updated yet just enjoy the pack and was sad to see it was throwing an error at start up.

**Comment by mFireworks** [comment]
Should be fixed with https://github.com/mFireworks/RenewableResources/commit/3bc57cc0b50e4399f1a49f110a2ed2e07169d7f5
See the latest release for the zip file, will publish to Modrinth shortly.
